name: Ruby Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual triggering
    inputs:
      test_type:
        description: 'Type of test to run'
        required: false
        default: 'all'
        type: choice
        options:
        - all
        - unit
        - coverage

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
        bundler-cache: true

    - name: Add Linux platform to bundle
      run: bundle lock --add-platform x86_64-linux

    - name: Run tests
      run: bundle exec rspec

    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage/
        retention-days: 30

    - name: Comment coverage on PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const path = require('path');
          
          // Read coverage summary
          const coveragePath = path.join('coverage', 'index.html');
          if (fs.existsSync(coveragePath)) {
            const coverage = fs.readFileSync(coveragePath, 'utf8');
            const match = coverage.match(/Line Coverage: (\d+\.?\d*)%/);
            if (match) {
              const percentage = match[1];
              const comment = `## 📊 Test Coverage Report\n\n**Line Coverage: ${percentage}%**\n\n✅ All tests passed!\n\nCoverage report available in workflow artifacts.`;
              
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: comment
              });
            }
          }
